server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: customer-service

  messages:
    basename: ValidationMessages
    encoding: UTF-8

  mongodb:
    uri: "mongodb://admin:admin123@localhost:27017/customerdb?authSource=admin"

  data:
    mongodb:
      auto-index-creation: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OIDC_ISSUER_URI:http://localhost:8180/realms/customer-microservice}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  file:
    name: logs/customer-service.log
  level:
    root: INFO
    dev.igorartsoft.customerservice: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.security: DEBUG