apiVersion: v1
kind: Secret
metadata:
  name: customer-service-secret
type: Opaque
stringData:
  MONGODB_URI: "mongodb://<mongo-user>:<mongo-password>@<mongodb-service>:27017/customerdb?authSource=admin"
  OIDC_ISSUER_URI: "https://<keycloak-route>/realms/customer-microservice"
