apiVersion: v1
kind: Secret
metadata:
  name: customer-mongodb-secret
  labels:
    app.kubernetes.io/name: customer-mongodb
    app.kubernetes.io/part-of: customer
    app.kubernetes.io/instance: customer-dev
    environment: dev
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: mongo_admin
  MONGO_INITDB_ROOT_PASSWORD: REPLACE_ME_DO_NOT_COMMIT_REAL_PASSWORD