apiVersion: v1
kind: Secret
metadata:
  name: customer-service-mongodb
  labels:
    app.kubernetes.io/name: customer-service
    app.kubernetes.io/part-of: customer
    app.kubernetes.io/instance: customer-dev
    environment: dev
type: Opaque
stringData:
  MONGODB_URI: mongodb://mongo_admin:REPLACE_ME_ENCODED_PASSWORD@customer-mongodb:27017/customerdb?authSource=admin